- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install packages
  apt:
    name: "{{ item }}"
  loop:
    - python3
    - git
    - vim
    - tmux
    - arduino
    - blender
    - darktable
    - gimp 
    - virtualbox
    - google-chrome-stable
